# Generated by Django 5.0.1 on 2024-01-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
