# Generated by Django 5.0.1 on 2024-01-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_name',
            new_name='name',
        ),
    ]
