# Generated by Django 5.0.1 on 2024-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0004_rename_company_name_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
